::: {.callout-note} 
In this section we provide some historic data and rudimentary analysis of the company during the 2019-2024 period.
:::

### **Historical Analysis of the Company** 

As we've identified in the previous sections, major events for the company in this peroid included the adoption of IGNITE strategy and recent cyberattack. Another major event was, of course, the global pandemic.

In terms of the corporation's life cycle, Clorox is definitely in the **Maturity** phase: it is relatively stable, resilient to shocks and demonstrates confidence during the recovery from such shocks. 

Getting historical data is very easy with R language - you just provide the time period you are interested in, and get it same as always.

```{r} 
#| echo: true
library(tidyquant)
library(ggplot2)
library(dplyr)

tickers <- c("CLX", "CL", "PG", "CHD", "KMB")

prices <- tq_get(tickers,
               from = "2019-01-01",
               to = "2024-12-31",
               get = "stock.prices")

prices |>
  ggplot(aes(x = date, y = adjusted, color = symbol)) +
  geom_line() +
  labs(subtitle = "Simple stock price comparison for the last 5 years against major competitors")
```

Fundamental analysis based on revenue data for the last five-year period can be found in the "Fundamental Analysis" section.

---

Sites like [https://stockanalysis.com](https://stockanalysis.com) provide all kinds of historic data for the last five-year period in nice tables. All of it can be scraped - we'll scrape and reproduce some of it here.

| Fiscal Year                             | Current              | FY 2024              | FY 2023              | FY 2022              | FY 2021              | FY 2020              |
|-----------------------------------------|----------------------|----------------------|----------------------|----------------------|----------------------|----------------------|
| Period Ending                           | Feb '25 Feb 14, 2025 | Jun '24 Jun 30, 2024 | Jun '23 Jun 30, 2023 | Jun '22 Jun 30, 2022 | Jun '21 Jun 30, 2021 | Jun '20 Jun 30, 2020 |
| Market Capitalization                   | 18,222               | 16,948               | 19,661               | 17,352               | 22,376               | 27,626               |
| Market Cap Growth                       | 13.64%               | -13.80%              | 13.31%               | -22.45%              | -19.00%              | 41.66%               |
| Enterprise Value                        | 21,024               | 19,913               | 22,613               | 20,467               | 25,241               | 30,412               |
| Last Close Price                        | 147.92               | 133.25               | 150.09               | 128.86               | 159.95               | 190.95               |
| PE Ratio                                | 40.32                | 60.53                | 131.95               | 37.56                | 31.52                | 29.42                |
| Forward PE                              | 20.81                | 21.90                | 29.44                | 28.13                | 25.00                | 30.85                |
| PS Ratio                                | 2.56                 | 2.39                 | 2.66                 | 2.44                 | 3.05                 | 4.11                 |
| PB Ratio                                | 166.14               | 34.45                | 50.67                | 23.80                | 37.80                | 30.43                |

: CLX's Historical Financial Ratios, source: @CloroxCompanyCLXc {.striped .hover}

### **Conclusion**

We can use publicly available data, as well as the R language to get historical financial data and ratios. The analysis shows strong performance during the last five-year period.
