### **Analysis Summary and Letter Grade**

Our analysis shows mature company with stable management, good branding, strong fundamentals and good estimated prospects. We give the letter grade **B** for the company and recommend including its stock in the investment portfolio. Of course, no one single stock should be recommended individually for investment, but portfolio management is out of scope for this document.

### **Advice for the Fiduciary**
This document provides the fiduciary with basic tools for the quantitative analysis of individual corporations. These tools are indeed **basic** and should only be viewed as a starting point for serious analysis. There are many great ways to learn more about finance and investment. We would recommend to look at the following sources (which we ourselves used to prepare this document) to learn more: [@QuantitativeFinancea], [@wahlenFinancialReportingFinancial2022], [@ForecastingPrinciplesPractice], [@DataScience2e], [@TidyQuantitativeFinancial], [@Investopedia].
