<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.40">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="keywords" content="Financial Report, Feduciary, Course Project">

<title>Research Report on the Clorox Company (CLX)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-549806ee2085284f45b00abea8c6df48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-bac1c56864119d97d87e9872e9e076ce.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta name="citation_title" content="Research Report on the Clorox Company (CLX)">
<meta name="citation_abstract" content="In September 2021, a significant jump in seismic activity on the island of La Palma (Canary Islands, Spain) signaled the start of a volcanic crisis that still continues at the time of writing. Earthquake data is continually collected and published by the Instituto Geográphico Nacional (IGN). ...
">
<meta name="citation_keywords" content="Financial Report,Feduciary,Course Project">
<meta name="citation_author" content="Andrey Malyukov">
<meta name="citation_author" content="Roza Bass">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=10-K Annual Report Thu Aug 08 2024;,citation_abstract=Clorox Co (CLX) SEC Filing 10-K Annual Report for the fiscal year ending Sunday, June 30, 2024;,citation_language=en-US;,citation_journal_title=Last10K.com;,citation_publisher=https://last10k.com/sec-filings/clx/0000021076-24-000030.htm;">
<meta name="citation_reference" content="citation_title=10-Q Quarterly Report Mon Feb 03 2025;,citation_abstract=Clorox Co (CLX) SEC Filing 10-Q Quarterly Report for the period ending Tuesday, December 31, 2024;,citation_language=en-US;,citation_journal_title=Last10K.com;,citation_publisher=https://last10k.com/sec-filings/clx/0000021076-25-000013.htm;">
<meta name="citation_reference" content="citation_title=8.7 ARIMA modelling in R  Forecasting: Principles and Practice (2nd ed);,citation_abstract=2nd edition;">
<meta name="citation_reference" content="citation_title=Apple’s SWOT analysis: Stock faces AI challenges amid strong ecosystem By Investing.com;,citation_abstract=Apple’s SWOT analysis: stock faces AI challenges amid strong ecosystem;,citation_language=en-US;,citation_journal_title=Investing.com;,citation_publisher=https://www.investing.com/news/swot-analysis/cloroxs-swot-analysis-stock-faces-challenges-amid-market-share-gains-3847534;">
<meta name="citation_reference" content="citation_title=Clorox Faces Mixed Analyst Outlook Amid Cyberattack and Market Challenges;,citation_abstract=The Clorox Company remains a critical focal point for Wall Street analysts as they assess the consumer goods giant’s strategic maneuvers and market performance amidst a rapidly changing financial…;,citation_author=Eric Blancaro;,citation_publication_date=2024-09;,citation_cover_date=2024-09;,citation_year=2024;,citation_language=en-GB;,citation_journal_title=The Financial Analyst;,citation_publisher=https://thefinancialanalyst.net/2024/09/22/clorox-faces-mixed-analyst-outlook-amid-cyberattack-and-market-challenges/;">
<meta name="citation_reference" content="citation_title=8 Reasons Why Forecasting Is Hard;,citation_abstract=Forecasting is a popular but difficult problem in data science. Challenges arise for several reasons, from non-stationarity to noise and missing values. Tackling these issues may be pivotal for improving forecasting performance. Introduction Atime series is a sequence of values ordered by time. The key aspect about these data sets is the temporal dependency among […];,citation_author=Vitor Cerqueira;,citation_publication_date=2022-11;,citation_cover_date=2022-11;,citation_year=2022;,citation_language=en-US;,citation_journal_title=Towards Data Science;,citation_publisher=https://towardsdatascience.com/8-reasons-why-forecasting-is-hard-481755a05325/;">
<meta name="citation_reference" content="citation_title=Charting with tidyquant;,citation_language=en-US;,citation_publisher=https://business-science.github.io/tidyquant/articles/TQ04-charting-with-tidyquant.html;">
<meta name="citation_reference" content="citation_title=The Clorox Company: Business Model, SWOT Analysis, and Competitors 2024 - PitchGrade;,citation_publisher=https://pitchgrade.com/companies/the-clorox-company;">
<meta name="citation_reference" content="citation_title=The Clorox Company (CLX) Company Profile &amp;amp;amp; Facts;,citation_abstract=See the company profile for The Clorox Company (CLX) including business summary, industry/sector information, number of employees, business summary, corporate governance, key executives and their compensation.;,citation_language=en-US;,citation_journal_title=Yahoo Finance;,citation_publisher=https://finance.yahoo.com/quote/CLX/profile/;">
<meta name="citation_reference" content="citation_title=The Clorox Company (CLX) Leadership &amp;amp;amp; Management Team Analysis;,citation_abstract=Learn about The Clorox Company (CLX) stock’s management team. Comprehensive performance, salary and tenure analysis for the CEO, board and leadership team.;,citation_language=en-US;,citation_journal_title=Simply Wall St;,citation_publisher=https://simplywall.st/stocks/us/household/nyse-clx/clorox/management;">
<meta name="citation_reference" content="citation_title=The Clorox Company Competitors and comparisons of Financial Results from MRQ;,citation_publisher=https://csimarket.com/stocks/competition2.php?code=CLX;">
<meta name="citation_reference" content="citation_title=The Clorox Company (LON:0I0J) Company Profile &amp;amp;amp; Overview;,citation_abstract=Company profile for The Clorox Company (LON:0I0J) with a description, list of executives, contact details and other key facts.;,citation_language=en-US;,citation_journal_title=Stock Analysis;,citation_publisher=https://stockanalysis.com/quote/lon/0I0J/company/;">
<meta name="citation_reference" content="citation_title=The Clorox Market share relative to its competitors, as of Q4 2024 - CSIMarket;,citation_abstract=The Clorox’s Q4 2024 quarter and 12 months market share, relative to the CLX’s competitors. Based on total revenues.;,citation_language=en-US;,citation_publisher=https://csimarket.com/stocks/competitionSEG2.php?code=CLX;">
<meta name="citation_reference" content="citation_title=CLX - Clorox Co Stock Price Forecast 2025, 2026, 2030 to 2050;,citation_abstract=Explore CLX - Clorox Co Stock Price Forecast: Accurate short-term and long-term price predictions up to 2050;,citation_language=en-US;,citation_publisher=https://stockscan.io/stocks/CLX/forecast;">
<meta name="citation_reference" content="citation_title=Comparing Iconic Indices: The S&amp;amp;amp;P 500 and DJIA;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_language=en-US;,citation_journal_title=The S;">
<meta name="citation_reference" content="citation_title=Consumer Defensive Stock Performance;,citation_abstract=Yahoo Finance’s Consumer Defensive performance dashboard help you quickly analyze &amp;amp;amp; examine stock performance across the Consumer Defensive sector using dozens of metrics and views.;,citation_language=en-US;,citation_journal_title=Yahoo Finance;,citation_publisher=https://finance.yahoo.com/sectors/consumer-defensive/;">
<meta name="citation_reference" content="citation_title=Tidyquant: Tidy Quantitative Financial Analysis;,citation_abstract=Bringing business and financial analysis to the ’tidyverse’. The ’tidyquant’ package provides a convenient wrapper to various ’xts’, ’zoo’, ’quantmod’, ’TTR’ and ’PerformanceAnalytics’ package functions and returns the objects in the tidy ’tibble’ format. The main advantage is being able to use quantitative functions with the ’tidyverse’ functions including ’purrr’, ’dplyr’, ’tidyr’, ’ggplot2’, ’lubridate’, etc. See the ’tidyquant’ website for more information, documentation and examples.;,citation_author=Matt Dancho;,citation_author=Davis Vaughan;,citation_publication_date=2025-02;,citation_cover_date=2025-02;,citation_year=2025;">
<meta name="citation_reference" content="citation_title=Evaluating Clorox: Insights From 11 Financial Analysts  Nasdaq;,citation_publisher=https://www.nasdaq.com/articles/evaluating-clorox-insights-11-financial-analysts;">
<meta name="citation_reference" content="citation_title=Financial modeling with R;,citation_publisher=https://mlozanoqf.github.io/tutorial_pmf/;">
<meta name="citation_reference" content="citation_title=Forecasting and predictive analytics: A critical look at the basic building blocks of a predictive model;,citation_language=en-US;,citation_journal_title=Brookings;,citation_publisher=https://www.brookings.edu/articles/forecasting-and-predictive-analytics-a-critical-look-at-the-basic-building-blocks-of-a-predictive-model/;">
<meta name="citation_reference" content="citation_title=How to download stock prices in R :: Coding Finance —;,citation_language=en-US;,citation_journal_title=How to download stock prices in R;,citation_publisher=https://www.codingfinance.com/post/2018-03-27-download-price/;">
<meta name="citation_reference" content="citation_title=IGNITE Strategy;,citation_abstract=The Clorox Company champions people to be well &amp;amp;amp; thrive every single day. Get company news, learn what’s in our products and search job opportunities.;,citation_language=en-US;,citation_journal_title=The Clorox Company;">
<meta name="citation_reference" content="citation_title=Investors  The Clorox Company;,citation_publisher=https://investors.thecloroxcompany.com/financial-reporting/annual-reports/default.aspx;">
<meta name="citation_reference" content="citation_title=Investors  The Clorox Company;,citation_publisher=https://investors.thecloroxcompany.com/financial-reporting/annual-reports/default.aspx;">
<meta name="citation_reference" content="citation_title=Macroeconomic Analysis with R at Claremont Graduate University;,citation_abstract=Macroeconomics at Claremont Graduate University;,citation_language=en-US;,citation_journal_title=macroLectures;,citation_publisher=https://hisamsabouni.github.io/macroLectures/;">
<meta name="citation_reference" content="citation_title=Clorox Operations Disrupted By Cyber-Attack;,citation_abstract=The cyber-attack disrupted manufacturing and distribution processes;,citation_author=Alessandro Mascellino;,citation_publication_date=2023-08;,citation_cover_date=2023-08;,citation_year=2023;,citation_language=en-GB;,citation_journal_title=Infosecurity Magazine;,citation_publisher=https://www.infosecurity-magazine.com/news/clorox-disrupted-cyber-attack/;">
<meta name="citation_reference" content="citation_title=Performance Analysis with tidyquant;,citation_language=en-US;,citation_publisher=https://business-science.github.io/tidyquant/articles/TQ05-performance-analysis-with-tidyquant.html;">
<meta name="citation_reference" content="citation_title=R: The R Project for Statistical Computing;,citation_publisher=https://www.r-project.org/;">
<meta name="citation_reference" content="citation_title=Purpose &amp;amp;amp; Values;,citation_abstract=The Clorox Company champions people to be well &amp;amp; thrive every single day. Get company news, learn what’s in our products and search job opportunities.;,citation_language=en-US;,citation_journal_title=The Clorox Company;">
<meta name="citation_reference" content="citation_title=Quarto;,citation_abstract=An open source technical publishing system for creating beautiful articles, websites, blogs, books, slides, and more. Supports Python, R, Julia, and JavaScript.;,citation_language=en-US;,citation_journal_title=Quarto;,citation_publisher=https://quarto.org/;">
<meta name="citation_reference" content="citation_title=Recognitions;,citation_abstract=Here are a few recent accomplishments we’re particularly proud of.;,citation_language=en-US;,citation_journal_title=The Clorox Company;">
<meta name="citation_reference" content="citation_title=Visualization Sector Trends with R Code;,citation_abstract=Welcome to a year-end installment of Reproducible Finance with R, a series posts that will be a little bit different from the norm on Alpha Architect (see here;,citation_author=Jonathan Regenstein;,citation_publication_date=2020-01;,citation_cover_date=2020-01;,citation_year=2020;,citation_language=en-US;,citation_journal_title=Alpha Architect;,citation_publisher=https://alphaarchitect.com/2020/01/visualization-sector-trends-with-r-code/;">
<meta name="citation_reference" content="citation_title=Responsibility;,citation_abstract=The Clorox Company champions people to be well &amp;amp;amp; thrive every single day. Get company news, learn what’s in our products and search job opportunities.;,citation_language=en-US;,citation_journal_title=The Clorox Company;">
</head>

<body>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-page-right">
      <h1 class="title">Research Report on the Clorox Company (CLX)</h1>
            <p class="subtitle lead">A Final Project for the Computational Finance Cource</p>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
            <div class="quarto-title-meta-author column-page-right">
          <div class="quarto-title-meta-heading">Authors</div>
          <div class="quarto-title-meta-heading">Affiliation</div>
          
                <div class="quarto-title-meta-contents">
            <p class="author">Andrey Malyukov <a href="mailto:ds-an@tuta.io" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Sami Shamoon College of Engineering
                      </p>
                  </div>
                      <div class="quarto-title-meta-contents">
            <p class="author">Roza Bass </p>
          </div>
                <div class="quarto-title-meta-contents">
                    <p class="affiliation">
                        Sami Shamoon College of Engineering
                      </p>
                  </div>
                    </div>
        
        <div class="quarto-title-meta column-page-right">

                      
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      <div class="quarto-alternate-formats"><div class="quarto-title-meta-heading">Other Formats</div><div class="quarto-title-meta-contents"><p><a href="report-malyukov-bass.docx"><i class="bi bi-file-word"></i>MS Word</a></p></div><div class="quarto-title-meta-contents"><p><a href="report-malyukov-bass.pdf"><i class="bi bi-file-pdf"></i>PDF</a></p></div><div class="quarto-title-meta-contents"><p><a href="bundle-malyukov-bass.zip" data-meca-link="true"><i class="bi bi-archive"></i>MECA Bundle</a></p></div></div></div>
    </div>

    <div>
      <div class="abstract">
        <div class="block-title">Abstract</div>
        <p>In September 2021, a significant jump in seismic activity on the island of La Palma (Canary Islands, Spain) signaled the start of a volcanic crisis that still continues at the time of writing. Earthquake data is continually collected and published by the Instituto Geográphico Nacional (IGN). …</p>
      </div>
    </div>

    <div>
      <div class="keywords">
        <div class="block-title">Keywords</div>
        <p>Financial Report, Feduciary, Course Project</p>
      </div>
    </div>

    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-full toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#todo" id="toc-todo" class="nav-link active" data-scroll-target="#todo">TODO</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#section" id="toc-section" class="nav-link" data-scroll-target="#section"></a></li>
  <li><a href="#sector-analysis" id="toc-sector-analysis" class="nav-link" data-scroll-target="#sector-analysis">Sector Analysis</a></li>
  <li><a href="#section-1" id="toc-section-1" class="nav-link" data-scroll-target="#section-1"></a>
  <ul class="collapse">
  <li><a href="#financial-analysis-of-the-clorox-company-clx-in-the-consumer-defensive-sector" id="toc-financial-analysis-of-the-clorox-company-clx-in-the-consumer-defensive-sector" class="nav-link" data-scroll-target="#financial-analysis-of-the-clorox-company-clx-in-the-consumer-defensive-sector">Financial Analysis of The Clorox Company (CLX) in the Consumer Defensive Sector</a></li>
  </ul></li>
  <li><a href="#personality-of-the-company" id="toc-personality-of-the-company" class="nav-link" data-scroll-target="#personality-of-the-company">Personality of the Company</a></li>
  <li><a href="#section-2" id="toc-section-2" class="nav-link" data-scroll-target="#section-2"></a></li>
  <li><a href="#fundamental-analysis" id="toc-fundamental-analysis" class="nav-link" data-scroll-target="#fundamental-analysis">Fundamental Analysis</a></li>
  <li><a href="#section-3" id="toc-section-3" class="nav-link" data-scroll-target="#section-3"></a></li>
  <li><a href="#technical-analysis" id="toc-technical-analysis" class="nav-link" data-scroll-target="#technical-analysis">Technical Analysis</a></li>
  <li><a href="#section-4" id="toc-section-4" class="nav-link" data-scroll-target="#section-4"></a></li>
  <li><a href="#company-performance-2019-2024" id="toc-company-performance-2019-2024" class="nav-link" data-scroll-target="#company-performance-2019-2024">Company Performance 2019-2024</a></li>
  <li><a href="#section-5" id="toc-section-5" class="nav-link" data-scroll-target="#section-5"></a>
  <ul class="collapse">
  <li><a href="#the-clorox-company-clx-performance-and-operations-analysis-20192024" id="toc-the-clorox-company-clx-performance-and-operations-analysis-20192024" class="nav-link" data-scroll-target="#the-clorox-company-clx-performance-and-operations-analysis-20192024">The Clorox Company (CLX) Performance and Operations Analysis (2019–2024)</a></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><strong>Key Takeaways</strong></a></li>
  </ul></li>
  <li><a href="#forecasting" id="toc-forecasting" class="nav-link" data-scroll-target="#forecasting">Forecasting</a></li>
  <li><a href="#section-6" id="toc-section-6" class="nav-link" data-scroll-target="#section-6"></a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#section-7" id="toc-section-7" class="nav-link" data-scroll-target="#section-7"></a></li>
  </ul>
<div class="quarto-alternate-notebooks"><h2>Notebooks</h2><ul><li><a href="notebooks/2019-2024-preview.html"><i class="bi bi-journal-code"></i>Company Performance 2019-2024</a></li><li><a href="notebooks/forecasting-preview.html"><i class="bi bi-journal-code"></i>Forecasting</a></li><li><a href="notebooks/fundamentals-preview.html"><i class="bi bi-journal-code"></i>Fundamental Analysis</a></li><li><a href="notebooks/intro-preview.html"><i class="bi bi-journal-code"></i>Introduction</a></li><li><a href="notebooks/personality-preview.html"><i class="bi bi-journal-code"></i>Personality of the Company</a></li><li><a href="notebooks/sector-preview.html"><i class="bi bi-journal-code"></i>Sector Analysis</a></li><li><a href="notebooks/summary-preview.html"><i class="bi bi-journal-code"></i>Summary</a></li><li><a href="notebooks/technical-preview.html"><i class="bi bi-journal-code"></i>Technical Analysis</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block column-page-right" id="quarto-document-content">



  


<!-- ## Section -->
<!-- This is a simple placeholder for the manuscript's main document [@knuth84]. -->
<section id="todo" class="level2">
<h2 class="anchored" data-anchor-id="todo">TODO</h2>
<p>Use “PerformanceAnalytics” package for Sharpe ratio and risk analysis.</p>
<p>Cite your stuff: <span class="citation" data-cites="regensteinVisualizationSectorTrends2020">(<a href="#ref-regensteinVisualizationSectorTrends2020" role="doc-biblioref">Regenstein 2020</a>)</span>.</p>
</section>
<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
</section>
<section id="section" class="level1 quarto-embed-nb-cell">
<h1></h1>
<blockquote class="blockquote">
<p><strong>On the simplified nature of analysis in this document.</strong></p>
<p>Subject of financial analysis is very information-dense and to perform such an analysis (be it an analysis of industrial sectors, fundamental, technical, etc.) in earnest is a non-trivial job that we don’t see ourselves capable of performing.</p>
<p>Therefore, this document aims to provide a simplified, non-rigorous analysis aiming to showcase our understanding of course material and minimal proficiency in scientific communication using tools such as R language <span class="citation" data-cites="ProjectStatisticalComputing"><span>“R: <span>The R Project</span> for <span>Statistical Computing</span>”</span> (<a href="#ref-ProjectStatisticalComputing" role="doc-biblioref">n.d.</a>)</span>, its “tidyquant” package <span class="citation" data-cites="danchoTidyquantTidyQuantitative2025">Dancho and Vaughan (<a href="#ref-danchoTidyquantTidyQuantitative2025" role="doc-biblioref">2025</a>)</span> and Quarto scientific publishing system <span class="citation" data-cites="Quarto"><span>“Quarto”</span> (<a href="#ref-Quarto" role="doc-biblioref">n.d.</a>)</span>.</p>
</blockquote>
<div id="b60f1751-58c9-4d99-85fb-242e509d91bb" class="cell">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/notebooks-intro-cell-2-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1"><img src="index_files/figure-html/notebooks-intro-cell-2-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>We need better stuff though.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "CPALTT01USQ657N"           CPALTT01USQ657N
1955-04-01       0.0000000
1955-07-01       0.4993758
1955-10-01       0.1242236
1956-01-01      -0.2481390
1956-04-01       0.8706468
1956-07-01       1.2330456     Index            CPALTT01USQ657N  
 Min.   :1955-04-01   Min.   :-2.8285  
 1st Qu.:1972-06-08   1st Qu.: 0.3950  
 Median :1989-08-16   Median : 0.8018  
 Mean   :1989-08-16   Mean   : 0.8959  
 3rd Qu.:2006-10-24   3rd Qu.: 1.1939  
 Max.   :2024-01-01   Max.   : 3.9508  </code></pre>
</div>
<div id="tbl-planets" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-planets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Astronomical object
</figcaption>
<div aria-describedby="tbl-planets-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display">
<div id="tbl-planets-1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-tbl figure">
<figcaption class="quarto-float-caption-top quarto-subfloat-caption quarto-subfloat-tbl" id="tbl-planets-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a)
</figcaption>
<div aria-describedby="tbl-planets-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="index_files/figure-html/notebooks-intro-tbl-planets-output-3.png" class="lightbox" data-gallery="tbl-planets" title="Table&nbsp;1&nbsp;(a): "><img src="index_files/figure-html/notebooks-intro-tbl-planets-output-3.png" id="tbl-planets-1" class="img-fluid figure-img" data-ref-parent="tbl-planets"></a>
</div>
</figure>
</div>
</div>
</div>
</figure>
</div>
</div>
<p>Use this kind of macroeconomic analysis maybe?</p>
</section>
<section id="sector-analysis" class="level2">
<h2 class="anchored" data-anchor-id="sector-analysis">Sector Analysis</h2>
<p>Performance of all sectors relative to each other.</p>
<p>https://alphaarchitect.com/2020/01/visualization-sector-trends-with-r-code/</p>
<p>Maybe that’s a bit much.</p>
</section>
<section id="section-1" class="level1 quarto-embed-nb-cell">
<h1></h1>
<!-- Add some stuff on turbulence and economic/social instability - can lift right out of 10-k or the quarterly report. -->
<section id="financial-analysis-of-the-clorox-company-clx-in-the-consumer-defensive-sector" class="level3">
<h3 class="anchored" data-anchor-id="financial-analysis-of-the-clorox-company-clx-in-the-consumer-defensive-sector">Financial Analysis of The Clorox Company (CLX) in the Consumer Defensive Sector</h3>
<section id="sector-analysis-1" class="level4">
<h4 class="anchored" data-anchor-id="sector-analysis-1"><strong>1. Sector Analysis</strong></h4>
<p>Clorox operates in the <strong>Consumer Defensive sector</strong>, specifically within the Household and Personal Products sub-sector. This sector is characterized by stable demand and recession resilience.</p>
<p>Sector’s <strong>Market Cap</strong> is estimated to be $3.7 trillion. The <strong>Market weight (share)</strong> of the sector relative to the other 10 sectors is 5.45%.</p>
<p>Sector’s <strong>Year-To-Date Return</strong> is 6.17%, which outperforms S&amp;P500 (3.54%).</p>
<hr>
</section>
<section id="position-relative-to-competitors" class="level4">
<h4 class="anchored" data-anchor-id="position-relative-to-competitors"><strong>2. Position Relative to Competitors</strong></h4>
<!-- Check these values -->
<!-- | **Metric**           | **Clorox (CLX)**      | **Colgate-Palmolive (CL)** | **Procter & Gamble (PG)** | **Industry Avg**       | -->
<!-- |----------------------|-----------------------|----------------------------|---------------------------|------------------------| -->
<!-- | **Revenue (FY24)**   | $7.09B   | $20.10B        | $84.04B       | Varies by sub-industry | -->
<!-- | **Net Margin**       | 6.38%    | 14.38%         | ~18% (est.)               | ~10-15%               | -->
<!-- | **P/E Ratio**        | 40.62    | 24.39          | 26.66         | 20-25                 | -->
<!-- | **Dividend Yield**   | 3.3%     | 2.3%           | 2.4%                      | 2.5-3.5%              | -->
<!-- Move Strengths/Weaknesses, emphasize market share -->
<p>Clorox’s market share inside it’s sector is relatively small:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 16%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>COMPANY NAME</th>
<th>MARKET SHARE 12 Months Ending Q4 2024</th>
<th>MARKET SHARE 12 Months Ending Q3 2024</th>
<th>MARKET SHARE MRQ Q4 2024</th>
<th>MARKET SHARE Q3 2024</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>The Clorox Company</strong></td>
<td>2.61%</td>
<td>2.80%</td>
<td>2.42 %</td>
<td>2.66 %</td>
</tr>
<tr class="even">
<td>The Campbells Company</td>
<td>3.60%</td>
<td>3.61%</td>
<td>3.97%</td>
<td>3.46%</td>
</tr>
<tr class="odd">
<td>Colgate palmolive Company</td>
<td>7.32%</td>
<td>7.54%</td>
<td>7.09%</td>
<td>7.59%</td>
</tr>
<tr class="even">
<td>Conagra Brands Inc</td>
<td>4.58%</td>
<td>4.61%</td>
<td>4.58%</td>
<td>4.21%</td>
</tr>
<tr class="odd">
<td>Ecolab Inc</td>
<td>5.06%</td>
<td>5.07%</td>
<td>5.26%</td>
<td>5.40%</td>
</tr>
<tr class="even">
<td>Mccormick and Company Incorporated</td>
<td>2.45%</td>
<td>2.50%</td>
<td>2.58%</td>
<td>2.53%</td>
</tr>
<tr class="odd">
<td>Procter and Gamble Co</td>
<td>30.72%</td>
<td>31.46%</td>
<td>31.37%</td>
<td>32.77%</td>
</tr>
<tr class="even">
<td>Hormel Foods Corporation</td>
<td>5.52%</td>
<td>5.65%</td>
<td>5.09%</td>
<td>4.37%</td>
</tr>
<tr class="odd">
<td>Avon Products Inc</td>
<td>1.15%</td>
<td>1.28%</td>
<td>0.95%</td>
<td>1.23%</td>
</tr>
<tr class="even">
<td>Horizon Kinetics Holding Corporation</td>
<td>0.01%</td>
<td>0.00%</td>
<td>0.02%</td>
<td>0.00%</td>
</tr>
<tr class="odd">
<td>Ingredion Incorporated</td>
<td>2.75%</td>
<td>2.89%</td>
<td>2.68%</td>
<td>2.83%</td>
</tr>
<tr class="even">
<td>Lancaster Colony Corporation</td>
<td>0.69%</td>
<td>0.70%</td>
<td>0.73%</td>
<td>0.70%</td>
</tr>
<tr class="odd">
<td>J and j Snack Foods Corp</td>
<td>0.58%</td>
<td>0.59%</td>
<td>0.52%</td>
<td>0.64%</td>
</tr>
<tr class="even">
<td>Treehouse Foods Inc</td>
<td>1.19%</td>
<td>1.24%</td>
<td>1.20%</td>
<td>1.19%</td>
</tr>
<tr class="odd">
<td>Dole Plc</td>
<td>3.00%</td>
<td>3.46%</td>
<td>3.00%</td>
<td>3.46%</td>
</tr>
<tr class="even">
<td>Church and Dwight Co Inc</td>
<td>2.22%</td>
<td>2.27%</td>
<td>2.27%</td>
<td>2.28%</td>
</tr>
<tr class="odd">
<td>Coty Inc</td>
<td>2.22%</td>
<td>2.30%</td>
<td>2.39%</td>
<td>2.52%</td>
</tr>
<tr class="even">
<td>Unilever Plc</td>
<td>24.32%</td>
<td>22.02%</td>
<td>24.32%</td>
<td>22.02%</td>
</tr>
<tr class="odd">
<td>SUBTOTAL</td>
<td>100%</td>
<td>100%</td>
<td>100%</td>
<td>100%</td>
</tr>
</tbody>
</table>
<p>CLX’s Market share relative to its competitors, as of Q4 2024 within the Consumer Non Cyclical Sector (i.e.&nbsp;Consumer Defensive), source: <span class="citation" data-cites="CloroxMarketShare"><span>“The <span>Clorox Market</span> Share Relative to Its Competitors, as of <span>Q4</span> 2024 - <span>CSIMarket</span>”</span> (<a href="#ref-CloroxMarketShare" role="doc-biblioref">n.d.</a>)</span></p>
<p>Clorox competes with major players such as <strong>Procter &amp; Gamble (PG)</strong>, <strong>Colgate-Palmolive (CL)</strong>, <strong>Church &amp; Dwight (CHD)</strong>, and <strong>Kimberly-Clark (KMB)</strong>.</p>
<div id="3a63f2ad-880c-46f5-97f4-01dc3fc19fc0" class="cell">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/notebooks-sector-cell-2-output-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="index_files/figure-html/notebooks-sector-cell-2-output-2.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
<hr>
<!-- #### **3. Economic Indicator Comparison** -->
<!-- Clorox’s performance relative to the **S&P 500** and **Dow Jones Industrial Average (DJIA)** highlights its defensive nature: -->
<!-- - **Beta**: 0.42 (less volatile than the market). -->
<!-- - **1-Year Stock Performance**: -3.3% (CLX) vs. +7.9% (S&P 500) and +15.05% (DJIA). -->
<!-- - **Dividend Growth**: 35 consecutive years of increases, outperforming many S&P 500 staples. -->
<!--TODO - provide charts for these-->
<!-- ```{r}  -->
<!-- # Load required libraries -->
<!-- library(tidyquant) -->
<!-- library(ggplot2) -->
<!-- library(dplyr) -->
<!---->
<!-- # Define the stock and benchmark tickers -->
<!-- stock_ticker <- "CLX"  # The Clorox Company -->
<!-- benchmark_tickers <- c("^GSPC", "^DJI")  # S&P 500 and Dow Jones Industrial Average -->
<!---->
<!-- # Set the date range (last 5 years) -->
<!-- end_date <- Sys.Date() -->
<!-- start_date <- seq(end_date, length = 2, by = "-5 years")[2] -->
<!---->
<!-- # Download historical data for the stock and benchmarks -->
<!-- stock_prices <- tq_get(stock_ticker, get = "stock.prices", from = start_date, to = end_date) -->
<!-- benchmark_prices <- tq_get(benchmark_tickers, get = "stock.prices", from = start_date, to = end_date) -->
<!---->
<!-- # Calculate daily returns for the stock -->
<!-- stock_returns <- stock_prices %>% -->
<!--     tq_transmute(select = adjusted, mutate_fun = periodReturn, period = "daily", col_rename = "stock_return") -->
<!---->
<!-- # Calculate daily returns for the benchmarks -->
<!-- benchmark_returns <- benchmark_prices %>% -->
<!--     group_by(symbol) %>% -->
<!--     tq_transmute(select = adjusted, mutate_fun = periodReturn, period = "daily", col_rename = "benchmark_return") -->
<!---->
<!-- # Merge stock returns with benchmark returns -->
<!-- combined_returns <- left_join(stock_returns, benchmark_returns, by = "date") -->
<!---->
<!-- # Calculate rolling beta (252-day window) for each benchmark -->
<!-- beta_values <- combined_returns %>% -->
<!--     group_by(symbol) %>% -->
<!--     tq_mutate(mutate_fun = runCor, x = stock_returns, y = benchmark_returns, n = 252) %>% -->
<!--     rename(beta = running_correlation) %>% -->
<!--     ungroup() -->
<!---->
<!-- # Plot the rolling beta values -->
<!-- ggplot(beta_values, aes(x = date, y = beta, color = symbol)) + -->
<!--     geom_line() + -->
<!--     labs(title = paste("5-Year Rolling Beta for", stock_ticker, "vs S&P 500 and DJIA"), -->
<!--          x = "Date", -->
<!--          y = "Beta", -->
<!--          color = "Benchmark") + -->
<!--     theme_minimal() -->
<!-- ``` -->
<hr>
</section>
<section id="strategic-and-financial-challenges" class="level4">
<h4 class="anchored" data-anchor-id="strategic-and-financial-challenges"><strong>4. Strategic and Financial Challenges</strong></h4>
<ul>
<li><strong>Cyberattack Impact</strong>: Caused a 20% Q1 FY24 sales decline, though recovery efforts restored ~90% market share by Q3 .</li>
<li><strong>Margin Recovery</strong>: Gross margin expanded to 46.5% in Q4 FY24, driven by cost savings .</li>
<li><strong>Divestitures</strong>: Sold non-core businesses (Argentina, VMS) to focus on high-growth segments .</li>
</ul>
<!-- Move this to other chapters -->
<hr>
<hr>
</section>
<section id="key-insights" class="level4">
<h4 class="anchored" data-anchor-id="key-insights"><strong>6. Key Insights</strong></h4>
<ul>
<li>Clorox’s valuation (P/E 40.6) reflects optimism about its recovery and IGNITE strategy but is expensive compared to peers .</li>
<li>Consumer Staples sector growth (CAGR 3.7% for cleaning products) supports long-term stability, but competition from eco-friendly brands (e.g., Seventh Generation) poses risks .</li>
<li>Clorox’s underperformance vs.&nbsp;indices highlights sector-specific challenges (inflation, supply chain) .</li>
</ul>
<hr>
<p>For real-time data, update the R code with current ticker prices and adjust the date range. The analysis underscores Clorox’s resilience in a defensive sector but signals caution due to margin pressures and competitive headwinds.</p>
</section>
</section>
</section>
<section id="personality-of-the-company" class="level2">
<h2 class="anchored" data-anchor-id="personality-of-the-company">Personality of the Company</h2>
</section>
<section id="section-2" class="level1 quarto-embed-nb-cell">
<h1></h1>
<!--
Put here who the board of directors are, cite some analysis.
Describe the cybersecurity incident, values, brands.
Cite a few articles + analysts average.
-->
<section id="company-purpose-and-responsibility" class="level4">
<h4 class="anchored" data-anchor-id="company-purpose-and-responsibility"><strong>1. Company Purpose and Responsibility</strong></h4>
<section id="company-purpose" class="level5">
<h5 class="anchored" data-anchor-id="company-purpose"><strong>1. Company Purpose</strong></h5>
<p>Clorox’s stated purpose is to “champion people to be well and thrive every single day” <span class="citation" data-cites="PurposeValues"><span>“Purpose &amp; <span>Values</span>”</span> (<a href="#ref-PurposeValues" role="doc-biblioref">n.d.</a>)</span>. As a health and wellness company, Clorox aims to make a meaningful and positive impact on the world by improving the health and safety of employees, consumers, and communities. All of this is reflected in their family-friendly and inclusive branding.</p>
</section>
<section id="responsibility-policies" class="level5">
<h5 class="anchored" data-anchor-id="responsibility-policies"><strong>2. Responsibility Policies</strong></h5>
<p>Clorox integrates environmental, social, and governance (ESG) goals into its core business strategy <span class="citation" data-cites="Responsibility"><span>“Responsibility”</span> (<a href="#ref-Responsibility" role="doc-biblioref">n.d.</a>)</span>. Key areas of focus include:</p>
<ul>
<li><strong>Healthy Lives</strong>: Promoting employee well-being, product stewardship, and transparency in ingredients.<br>
</li>
<li><strong>Clean World</strong>: Reducing greenhouse gas emissions, plastic waste, and transitioning to 100% renewable energy in U.S. and Canada operations.<br>
</li>
<li><strong>Thriving Communities</strong>: Ensuring pay equity, fostering diversity, and supporting community initiatives.</li>
</ul>
<p>Clorox has set ambitious targets, such as achieving net-zero emissions by 2050.</p>
</section>
<section id="ignite-strategy" class="level5">
<h5 class="anchored" data-anchor-id="ignite-strategy"><strong>3. IGNITE Strategy</strong></h5>
<p>The IGNITE strategy is Clorox’s long-term plan to drive what the company calls a “purpose-driven growth” <span class="citation" data-cites="IGNITEStrategy"><span>“<span>IGNITE Strategy</span>”</span> (<a href="#ref-IGNITEStrategy" role="doc-biblioref">n.d.</a>)</span> by aligning financial goals with ESG priorities. Key pillars include:</p>
<ul>
<li><strong>Fuel Growth</strong>: Leveraging technology and sustainability to generate cost savings and reinvest in brands.<br>
</li>
<li><strong>Innovate Experiences</strong>: Building purpose-driven brands and enhancing consumer experiences through personalized and sustainable products.<br>
</li>
<li><strong>Reimagine Work</strong>: Creating an inclusive workplace and simplifying operations to drive efficiency.<br>
</li>
<li><strong>Evolve Portfolio</strong>: Expanding into consumer megatrends like sustainability and wellness.</li>
</ul>
<p>The strategy also includes specific financial targets, such as 2-4% net sales growth and 11-13% free cash flow generation.</p>
</section>
</section>
<section id="key-executives-their-commitment-and-performance" class="level4">
<h4 class="anchored" data-anchor-id="key-executives-their-commitment-and-performance"><strong>2. Key Executives, Their Commitment and Performance</strong></h4>
<table class="caption-top table">
<colgroup>
<col style="width: 24%">
<col style="width: 54%">
<col style="width: 9%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Name</th>
<th>Title</th>
<th>Pay</th>
<th>Year Born</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ms.&nbsp;Linda J. Rendle</td>
<td>CEO &amp; Chairman</td>
<td>3.93M</td>
<td>1979</td>
</tr>
<tr class="even">
<td>Mr.&nbsp;Kevin B. Jacobsen</td>
<td>Executive VP &amp; CFO</td>
<td>1.91M</td>
<td>1967</td>
</tr>
<tr class="odd">
<td>Mr.&nbsp;Eric H. Reynolds</td>
<td>Executive VP and Chief Operating &amp; Strategy Officer</td>
<td>1.96M</td>
<td>1970</td>
</tr>
<tr class="even">
<td>Ms.&nbsp;Angela C. Hilt</td>
<td>Executive VP, Chief Legal Officer &amp; Corporate Secretary</td>
<td>1.45M</td>
<td>1972</td>
</tr>
<tr class="odd">
<td>Ms.&nbsp;Kirsten M. Marriner</td>
<td>Executive VP and Chief People &amp; Corporate Affairs Officer</td>
<td>1.54M</td>
<td>1973</td>
</tr>
<tr class="even">
<td>Ms.&nbsp;Laura E. Peck</td>
<td>VP, Chief Accounting Officer &amp; Corporate Controller</td>
<td>–</td>
<td>1977</td>
</tr>
<tr class="odd">
<td>Ms.&nbsp;Chau Banks</td>
<td>Senior VP and Chief Information &amp; Data Officer</td>
<td>–</td>
<td>1970</td>
</tr>
<tr class="even">
<td>Ms.&nbsp;Lisah Burhan</td>
<td>Vice President of Investor Relations</td>
<td>–</td>
<td>–</td>
</tr>
<tr class="odd">
<td>Mr.&nbsp;Eric Sean Schwartz</td>
<td>Senior VP &amp; Chief Marketing Officer</td>
<td>–</td>
<td>1972</td>
</tr>
<tr class="even">
<td>Mr.&nbsp;Erbie L. Foster Jr.</td>
<td>Chief Diversity Officer</td>
<td>–</td>
<td>–</td>
</tr>
</tbody>
</table>
<p>Key Executives, source: <span class="citation" data-cites="CloroxCompanyCLX"><span>“The <span>Clorox Company</span> (<span>CLX</span>) <span>Company Profile</span> &amp; <span>Facts</span>”</span> (<a href="#ref-CloroxCompanyCLX" role="doc-biblioref">n.d.</a>)</span></p>
<p>According to <span class="citation" data-cites="CloroxCompanyBusiness"><span>“The <span>Clorox Company</span>: <span>Business Model</span>, <span>SWOT Analysis</span>, and <span>Competitors</span> 2024 - <span>PitchGrade</span>”</span> (<a href="#ref-CloroxCompanyBusiness" role="doc-biblioref">n.d.</a>)</span>, CEO and Chairman Linda J. Rendle, as well as the other executives and board members have significant ownership stakes at the company, indicating high confidence in their business.</p>
<p>Financial analysis website Simply WallSt gives the upper management team at Clorox high marks on all 4 criteria: Compensation vs Market, Compensation vs Earnings, Experienced Management and Experienced Board <span class="citation" data-cites="CloroxCompanyCLXa"><span>“The <span>Clorox Company</span> (<span>CLX</span>) <span>Leadership</span> &amp; <span>Management Team Analysis</span>”</span> (<a href="#ref-CloroxCompanyCLXa" role="doc-biblioref">n.d.</a>)</span>.</p>
</section>
<section id="company-brand-and-reputation" class="level4">
<h4 class="anchored" data-anchor-id="company-brand-and-reputation"><strong>3. Company Brand and Reputation</strong></h4>
<p>Clorox is a globally recognized leader in the cleaning and consumer products industry, known for its trusted brands such as <strong>Clorox Bleach</strong>, <strong>Pine-Sol</strong>, <strong>Hidden Valley</strong>, <strong>Brita</strong>, and <strong>Burt’s Bees</strong>.</p>
<p>The company has received numerous accolades, including being named one of <strong>America’s Greenest Companies</strong> by Newsweek, a <strong>Safer Choice Partner of the Year</strong> by the EPA, and a top performer in the <strong>Human Rights Campaign Foundation’s Corporate Equality Index</strong>. Its sustainable brands, such as <strong>Brita</strong>, <strong>Burt’s Bees</strong>, and <strong>Green Works</strong>, have gained significant consumer trust for their eco-friendly and socially responsible practices <span class="citation" data-cites="Recognitions"><span>“Recognitions”</span> (<a href="#ref-Recognitions" role="doc-biblioref">n.d.</a>)</span>.</p>
<hr>
<p>In August 2023, Clorox experienced a severe <strong>cyberattack</strong> <span class="citation" data-cites="mascellinoCloroxOperationsDisrupted2023">Mascellino (<a href="#ref-mascellinoCloroxOperationsDisrupted2023" role="doc-biblioref">2023</a>)</span> that disrupted its IT systems and operations. The attack, which was detected on August 14, forced the company to take affected systems offline, leading to significant production delays and supply chain disruptions. Clorox activated its business continuity plans, reverting to manual processes for order fulfillment and customer communications.</p>
<p>The cyberattack had a material financial impact, with Clorox reporting a 23-28% decline in quarterly sales and a drop in its stock price by over 25% following the incident.</p>
<p>Clorox’s response to the cyberattack highlighted its crisis management capabilities. The company maintained transparency by providing regular updates to stakeholders and implementing phased recovery plans to restore operations safely. Brand and reputation were not severely damaged in the process.</p>
</section>
</section>
<section id="fundamental-analysis" class="level2">
<h2 class="anchored" data-anchor-id="fundamental-analysis">Fundamental Analysis</h2>
</section>
<section id="section-3" class="level1 quarto-embed-nb-cell">
<h1></h1>
<!--
Common size analysis for fundamental analysis.
Life cycle stage.
ROI for stock over a period of time.
Analyst's views and rating.
client.shwab.com
EBITDA
P/B ratio
EV = Mcap + Debt
-->
<hr>
<blockquote class="blockquote">
<p><strong>Important</strong></p>
<p>In this section we will take a look at quantitative fundamental analysis tools provided by the “tidyquant” R language package [<span class="citation" data-cites="danchoTidyquantTidyQuantitative2025">Dancho and Vaughan (<a href="#ref-danchoTidyquantTidyQuantitative2025" role="doc-biblioref">2025</a>)</span>] and use them to get key financial ratios of fundamental analysis for the Clorox company. This section is based on the following wonderful tutorial: <span class="citation" data-cites="PerformanceAnalysisTidyquant"><span>“Performance <span>Analysis</span> with Tidyquant”</span> (<a href="#ref-PerformanceAnalysisTidyquant" role="doc-biblioref">n.d.</a>)</span></p>
</blockquote>
<p>First let’s retrieve 5-year period returns from the prices adjusted for stock splits, both for Clorox and S&amp;P500 as the baseline. Next, we combine both datasets (Clorox and S&amp;P500 returns) using “left-join” on the “date” field. Using this dataset, we can retrieve all kind of fundamental metrics, such as <strong>Alpha</strong> (0.0008), <strong>Beta</strong> (0.414).</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-planet-measures</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: Astronomical object</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ purrr::%||%()   masks base::%||%()
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-planet-measures</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: Astronomical object</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyquant)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 
── Attaching core tidyquant packages ─────────────────────── tidyquant 1.0.10 ──
✔ PerformanceAnalytics 2.0.8      ✔ TTR                  0.24.4
✔ quantmod             0.4.26     ✔ xts                  0.14.1── Conflicts ────────────────────────────────────────── tidyquant_conflicts() ──
✖ purrr::%||%()                  masks base::%||%()
✖ zoo::as.Date()                 masks base::as.Date()
✖ zoo::as.Date.numeric()         masks base::as.Date.numeric()
✖ dplyr::filter()                masks stats::filter()
✖ xts::first()                   masks dplyr::first()
✖ dplyr::lag()                   masks stats::lag()
✖ xts::last()                    masks dplyr::last()
✖ PerformanceAnalytics::legend() masks graphics::legend()
✖ quantmod::summary()            masks base::summary()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-planet-measures</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: Astronomical object</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>Ra <span class="ot">&lt;-</span> <span class="st">"CLX"</span> <span class="sc">|&gt;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tq_get</span>(<span class="at">get  =</span> <span class="st">"stock.prices"</span>,</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">from =</span> <span class="st">"2020-01-01"</span>,</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">to   =</span> <span class="st">"2025-02-01"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(symbol) <span class="sc">|&gt;</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tq_transmute</span>(<span class="at">select     =</span> adjusted, </span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>                 <span class="at">mutate_fun =</span> periodReturn, </span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>                 <span class="at">period     =</span> <span class="st">"monthly"</span>, </span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>                 <span class="at">col_rename =</span> <span class="st">"Ra"</span>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>Rb <span class="ot">&lt;-</span> <span class="st">"^GSPC"</span> <span class="sc">|&gt;</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tq_get</span>(<span class="at">get  =</span> <span class="st">"stock.prices"</span>,</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>           <span class="at">from =</span> <span class="st">"2020-01-01"</span>,</span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>           <span class="at">to   =</span> <span class="st">"2025-02-01"</span>) <span class="sc">|&gt;</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tq_transmute</span>(<span class="at">select     =</span> adjusted, </span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>                 <span class="at">mutate_fun =</span> periodReturn, </span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>                 <span class="at">period     =</span> <span class="st">"monthly"</span>, </span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>                 <span class="at">col_rename =</span> <span class="st">"Rb"</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>RaRb <span class="ot">&lt;-</span> <span class="fu">left_join</span>(Ra, Rb, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"date"</span> <span class="ot">=</span> <span class="st">"date"</span>))</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>RaRb_capm <span class="ot">&lt;-</span> RaRb <span class="sc">%&gt;%</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    <span class="fu">tq_performance</span>(<span class="at">Ra =</span> Ra, </span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Rb =</span> Rb, </span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>                   <span class="at">performance_fun =</span> table.CAPM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Registered S3 method overwritten by 'robustbase':
  method          from     
  hatvalues.lmrob RobStatTM</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: tbl-planet-measures</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: Astronomical object</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>RaRb_capm <span class="sc">%&gt;%</span> <span class="fu">select</span>(symbol, Alpha, Beta)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code># A tibble: 1 × 3
# Groups:   symbol [1]
  symbol  Alpha  Beta
  &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;
1 CLX    0.0008 0.414</code></pre>
<p>We can also get the <strong>Annualized Sharpe Ratio and Returns</strong>, <strong>Types of Mean Return (Geometric, Arithmetic, etc.)</strong>, <strong>Kurtosis</strong>, as well as <strong>Maximum and Median Return</strong> by following the similar steps (no need for the baseline this time).</p>
<div id="abb58371-d8b5-430a-a4ff-bcadebbebb4a" class="cell">
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
# Groups:   symbol [1]
  symbol AnnualizedReturn `AnnualizedSharpe(Rf=0%)` AnnualizedStdDev
  &lt;chr&gt;             &lt;dbl&gt;                     &lt;dbl&gt;            &lt;dbl&gt;
1 CLX              0.0381                     0.153            0.249# A tibble: 1 × 17
# Groups:   symbol [1]
  symbol ArithmeticMean GeometricMean Kurtosis `LCLMean(0.95)` Maximum Median
  &lt;chr&gt;           &lt;dbl&gt;         &lt;dbl&gt;    &lt;dbl&gt;           &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
1 CLX            0.0056        0.0031     1.20         -0.0128   0.218 0.0054
# ℹ 10 more variables: Minimum &lt;dbl&gt;, NAs &lt;dbl&gt;, Observations &lt;dbl&gt;,
#   Quartile1 &lt;dbl&gt;, Quartile3 &lt;dbl&gt;, SEMean &lt;dbl&gt;, Skewness &lt;dbl&gt;,
#   Stdev &lt;dbl&gt;, `UCLMean(0.95)` &lt;dbl&gt;, Variance &lt;dbl&gt;</code></pre>
</div>
</div>
<!-- Put the values in the markdown tables, mention concepts of qualitative analysis -->
<section id="i.-graham-number-calculation" class="level4">
<h4 class="anchored" data-anchor-id="i.-graham-number-calculation"><strong>I. Graham Number Calculation</strong></h4>
<p>The Graham Number estimates a stock’s intrinsic value using earnings per share (EPS) and book value per share (BVPS):<br>
<strong>Formula</strong>:</p>
<p><span class="math inline">\(\text{Graham Number} = \sqrt{22.5 \times \text{EPS} \times \text{BVPS}}\)</span></p>
<ul>
<li><strong>EPS (TTM)</strong>: $3.67<br>
</li>
<li><strong>BVPS</strong>: $0.98 (Total Equity: $121M / Shares Outstanding: 123.19M)<br>
</li>
<li><strong>Calculation</strong>:<br>
<span class="math inline">\(\sqrt{22.5 \times 3.67 \times 0.98} = \sqrt{80.92} \approx \boxed{8.99}\)</span></li>
<li><strong>Interpretation</strong>: CLX’s current stock price (~$149.61) far exceeds the Graham Number, indicating potential overvaluation based on traditional metrics .</li>
</ul>
<hr>
</section>
<section id="ii.-key-financial-ratios" class="level4">
<h4 class="anchored" data-anchor-id="ii.-key-financial-ratios"><strong>II. Key Financial Ratios</strong></h4>
<table class="caption-top table">
<colgroup>
<col style="width: 9%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 31%">
<col style="width: 32%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Category</strong></th>
<th><strong>Ratio</strong></th>
<th><strong>CLX Value</strong></th>
<th><strong>Formula</strong></th>
<th><strong>Interpretation</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Profitability</strong></td>
<td>Gross Profit Margin</td>
<td>44.51%</td>
<td>(Revenue - COGS) / Revenue</td>
<td>Stable gross margins despite cost inflation, supported by cost-saving initiatives .</td>
</tr>
<tr class="even">
<td></td>
<td>Operating Profit Margin</td>
<td>14.32%</td>
<td>Operating Income / Revenue</td>
<td>Margin expansion driven by divestitures and operational recovery post-cyberattack .</td>
</tr>
<tr class="odd">
<td></td>
<td>Net Profit Margin</td>
<td>6.38%</td>
<td>Net Income / Revenue</td>
<td>Lower than peers (e.g., P&amp;G: ~18%), reflecting cyberattack recovery costs .</td>
</tr>
<tr class="even">
<td></td>
<td>Return on Assets (ROA)</td>
<td>11.17%</td>
<td>Net Income / Avg. Total Assets</td>
<td>Efficient asset utilization, though impacted by divestitures .</td>
</tr>
<tr class="odd">
<td></td>
<td>Return on Equity (ROE)</td>
<td>276.11%</td>
<td>Net Income / Avg. Shareholders’ Equity</td>
<td>Artificially high due to low equity base ($121M) .</td>
</tr>
<tr class="even">
<td><strong>Liquidity</strong></td>
<td>Current Ratio</td>
<td>0.94</td>
<td>Current Assets / Current Liabilities</td>
<td>Below industry norms (1.5–3.0), indicating liquidity strain .</td>
</tr>
<tr class="odd">
<td></td>
<td>Quick Ratio</td>
<td>0.52</td>
<td>(Cash + Receivables) / Current Liabilities</td>
<td>Limited near-term liquidity, with heavy reliance on receivables .</td>
</tr>
<tr class="even">
<td><strong>Solvency</strong></td>
<td>Debt-to-Equity Ratio</td>
<td>25.55</td>
<td>Total Liabilities / Shareholders’ Equity</td>
<td>Extremely high leverage (vs.&nbsp;industry median ~1.0), raising solvency concerns .</td>
</tr>
<tr class="odd">
<td></td>
<td>Debt-to-Assets Ratio</td>
<td>98%</td>
<td>Total Liabilities / Total Assets</td>
<td>Nearly all assets financed by debt, increasing bankruptcy risk .</td>
</tr>
<tr class="even">
<td></td>
<td>Interest Coverage Ratio</td>
<td>~11.7</td>
<td>Operating Income / Interest Expense</td>
<td>Strong coverage due to operational recovery, but debt levels remain risky.</td>
</tr>
<tr class="odd">
<td><strong>Efficiency</strong></td>
<td>Asset Turnover Ratio</td>
<td>1.25</td>
<td>Revenue / Avg. Total Assets</td>
<td>Efficient asset use, though lower than pre-cyberattack levels .</td>
</tr>
<tr class="even">
<td></td>
<td>Inventory Turnover Ratio</td>
<td>6.38</td>
<td>COGS / Avg. Inventory</td>
<td>Healthy turnover, but down from 7.57 in 2020 .</td>
</tr>
<tr class="odd">
<td></td>
<td>Receivables Turnover Ratio</td>
<td>~11.05</td>
<td>Revenue / Avg. Accounts Receivable</td>
<td>Faster collections than industry median (~30 days) .</td>
</tr>
<tr class="even">
<td><strong>Valuation</strong></td>
<td>P/E Ratio</td>
<td>40.50</td>
<td>Price per Share / EPS</td>
<td>High vs.&nbsp;peers (PG: 26.66, CL: 24.39), reflecting recovery optimism .</td>
</tr>
<tr class="odd">
<td></td>
<td>P/B Ratio</td>
<td>61.19</td>
<td>Price per Share / Book Value per Share</td>
<td>Extremely high, driven by low equity base and market premium .</td>
</tr>
<tr class="even">
<td></td>
<td>P/S Ratio</td>
<td>2.59</td>
<td>Price per Share / Revenue per Share</td>
<td>Aligns with sector norms (Consumer Staples avg: ~2.5–3.0) .</td>
</tr>
<tr class="odd">
<td></td>
<td>Dividend Yield</td>
<td>3.26%</td>
<td>Annual Dividend / Price per Share</td>
<td>Attractive yield, supported by 48-year dividend growth streak .</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="iii.-key-insights" class="level4">
<h4 class="anchored" data-anchor-id="iii.-key-insights"><strong>III. Key Insights</strong></h4>
<ol type="1">
<li><strong>Profitability</strong>: Margins are recovering post-cyberattack, but net margins lag competitors. Gross margin improved to 43.8% in Q2 FY25, with cost savings offsetting inflation .<br>
</li>
<li><strong>Liquidity Risks</strong>: Low current (0.94) and quick (0.52) ratios highlight liquidity challenges, though improved cash flow ($401M YTD) provides relief .<br>
</li>
<li><strong>Debt Concerns</strong>: Debt-to-equity (25.55) and debt-to-assets (98%) ratios signal high leverage, though interest coverage (11.7x) remains manageable .<br>
</li>
<li><strong>Valuation</strong>: Elevated P/E (40.5) and P/B (61.19) suggest market optimism about Clorox’s recovery, but Graham Number ($8.99) implies overvaluation .<br>
</li>
<li><strong>Dividend Strength</strong>: A 3.26% yield with consistent growth underscores Clorox’s defensive appeal, despite a high payout ratio (133%) .</li>
</ol>
<hr>
</section>
<section id="iv.-conclusion" class="level4">
<h4 class="anchored" data-anchor-id="iv.-conclusion"><strong>IV. Conclusion</strong></h4>
<p>Clorox’s fundamentals reflect a company in recovery, balancing strong brand equity and dividend reliability with significant debt and valuation risks. While operational improvements (e.g., margin expansion, ERP transition) are promising, the stock’s premium pricing and leverage warrant caution. Investors should monitor debt reduction and margin sustainability in 2025 .</p>
</section>
</section>
<section id="technical-analysis" class="level2">
<h2 class="anchored" data-anchor-id="technical-analysis">Technical Analysis</h2>
</section>
<section id="section-4" class="level1 quarto-embed-nb-cell">
<h1></h1>
<!--
See "technical overview example" in notes. 
Use The Relative Strength Index (RSI).
Overbought/oversold analysis. 
Beta value for 5 years. Open, close, range, average volume, put/call ratios.
Return for ETF vs return for stock over time.
Stock correlation calculator?
Maybe just copy from here: https://mlozanoqf.github.io/tutorial_pmf/#technical-analysis.
-->
<blockquote class="blockquote">
<p><strong>Important</strong></p>
<p>Technical analysis in this section follows the wonderful tutorial provided here: [<span class="citation" data-cites="FinancialModelingb"><span>“Financial Modeling with <span>R</span>”</span> (<a href="#ref-FinancialModelingb" role="doc-biblioref">n.d.</a>)</span>]</p>
</blockquote>
<p>We’ll start with providing a simple plot of stock price movement.</p>
<div id="979de4c9-b6be-471c-8eb3-b87f4b2f0d98" class="cell">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/notebooks-technical-cell-2-output-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4"><img src="index_files/figure-html/notebooks-technical-cell-2-output-2.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>To identify basic trend in this movement, we then chart the <strong>Simple Moving Average</strong>.</p>
<div id="ec06792a-4bec-4ba7-b1dd-e91590e6e6c1" class="cell">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/notebooks-technical-cell-3-output-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5"><img src="index_files/figure-html/notebooks-technical-cell-3-output-1.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>By playing with the “n” value - the average of the last n-day stock prices - we produced a line that closely resembles the price line. Since the SMA line crosses the price line from top to bottom, we’re supposed to anticipate a drop in the stock price.</p>
<p><strong>The Bollinger Bands</strong> is another useful tool of technical analysis. These are “envelopes plotted at a standard deviation level above and below a simple moving average of the price” [<span class="citation" data-cites="FinancialModelingb"><span>“Financial Modeling with <span>R</span>”</span> (<a href="#ref-FinancialModelingb" role="doc-biblioref">n.d.</a>)</span>]. They supposed to show the volatility of a price of the stock and the size of expected change of the price in the future.</p>
<p>Let’s demonstrate.</p>
<div id="eae7d62f-751c-4bfd-8e07-d49c9bb860f0" class="cell">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/notebooks-technical-cell-4-output-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6"><img src="index_files/figure-html/notebooks-technical-cell-4-output-2.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>And finally let’s look at such charts for major competitors to get the feel of the market.</p>
<div id="96bd3ec6-8a3b-4155-982c-580c9a195a0b" class="cell">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/notebooks-technical-cell-5-output-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7"><img src="index_files/figure-html/notebooks-technical-cell-5-output-2.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
<p>As we can see, the volatility of the stock prices shouldn’t be that great in the near future. Since technical analysis is best-suited for short-term trading, near future is all we can advise or client on based on such analysis.</p>
</section>
<section id="company-performance-2019-2024" class="level2">
<h2 class="anchored" data-anchor-id="company-performance-2019-2024">Company Performance 2019-2024</h2>
</section>
<section id="section-5" class="level1 quarto-embed-nb-cell">
<h1></h1>
<section id="the-clorox-company-clx-performance-and-operations-analysis-20192024" class="level3">
<h3 class="anchored" data-anchor-id="the-clorox-company-clx-performance-and-operations-analysis-20192024">The Clorox Company (CLX) Performance and Operations Analysis (2019–2024)</h3>
<section id="financial-performance-overview" class="level4">
<h4 class="anchored" data-anchor-id="financial-performance-overview"><strong>1. Financial Performance Overview</strong></h4>
<p><strong>Revenue Trends</strong>:<br>
- <strong>2019–2024 Revenue</strong>: Clorox’s revenue grew from $6.21B in 2019 to $7.09B in FY2024 (June year-end), with volatility driven by macroeconomic challenges and a 2023 cyberattack. Key highlights:<br>
- <strong>2021 Peak</strong>: Revenue reached $7.34B (+9.2% YoY) due to pandemic-driven demand for cleaning products .<br>
- <strong>Post-Cyberattack Decline</strong>: FY2024 revenue fell 4% YoY to $7.09B, primarily due to supply chain disruptions and volume losses .<br>
- <strong>Q4 2024 Recovery</strong>: Quarterly revenue rebounded to $1.76B in Q3 2024 (+27.1% YoY), signaling recovery efforts .</p>
<p><strong>Profitability Metrics</strong>:<br>
- <strong>Gross Margin</strong>: Improved from 35.8% in FY2022 to 43.2% in FY2024, driven by cost-saving initiatives and pricing strategies .<br>
- <strong>Net Margin</strong>: Declined from 13.97% in FY2020 to 6.38% in FY2024, reflecting cyberattack recovery costs and divestiture impacts .<br>
- <strong>Operating Income</strong>: Dropped from $1.25B in FY2020 to $921M in FY2024, impacted by higher SG&amp;A expenses and restructuring .</p>
<p><strong>Key Ratios</strong>:<br>
| Metric | FY2020 | FY2024 | Change |<br>
|———————-|————–|————–|————–|<br>
| <strong>ROE</strong> | 128.02% | 276.11% | +148.09% |<br>
| <strong>Debt-to-Equity</strong> | 3.45 | 25.55 | +640% |<br>
| <strong>Current Ratio</strong> | 1.42 | 0.94 | -34% |<br>
| <strong>Dividend Yield</strong> | 2.25% | 3.26% | +1.01% |<br>
<em>Data sourced from financial statements and ratio analysis .</em></p>
<hr>
</section>
<section id="strategic-initiatives-and-operational-challenges" class="level4">
<h4 class="anchored" data-anchor-id="strategic-initiatives-and-operational-challenges"><strong>2. Strategic Initiatives and Operational Challenges</strong></h4>
<p><strong>Cyberattack Recovery</strong>:<br>
- The August 2023 cyberattack caused a 20% Q1 FY2024 sales decline, but Clorox restored ~90% market share by Q3 FY2024 through supply chain rebuilding and aggressive marketing .</p>
<p><strong>Portfolio Optimization</strong>:<br>
- <strong>Divestitures</strong>: Sold non-core businesses (Argentina in 2023, Better Health VMS in 2024) to focus on high-margin segments like cleaning and household products .<br>
- <strong>Innovation</strong>: Launched products like Clorox Toilet Bomb Cleaner and Glad ForceFlex Scented Trash Bags to drive brand relevance .</p>
<p><strong>Cost Management</strong>:<br>
- Achieved <strong>7 consecutive quarters of gross margin expansion</strong> by FY2024, supported by $100M annual savings from a streamlined operating model .<br>
- Reduced SG&amp;A expenses to 15–16% of sales in FY2025 (vs.&nbsp;17–18% pre-2023) .</p>
<hr>
</section>
<section id="liquidity-and-solvency-risks" class="level4">
<h4 class="anchored" data-anchor-id="liquidity-and-solvency-risks"><strong>3. Liquidity and Solvency Risks</strong></h4>
<ul>
<li><strong>Debt Surge</strong>: Debt-to-equity ratio soared to 25.55 in FY2024 (vs.&nbsp;industry median ~1.0), driven by cyberattack recovery costs and share buybacks .<br>
</li>
<li><strong>Liquidity Strain</strong>: Current ratio fell to 0.94 (vs.&nbsp;1.42 in FY2020), with only $278M cash on hand in FY2024 .<br>
</li>
<li><strong>Dividend Sustainability</strong>: Payout ratio reached 133% in FY2024, raising concerns despite 48 consecutive years of dividend growth .</li>
</ul>
<hr>
</section>
<section id="market-position-and-competitive-landscape" class="level4">
<h4 class="anchored" data-anchor-id="market-position-and-competitive-landscape"><strong>4. Market Position and Competitive Landscape</strong></h4>
<ul>
<li><strong>Market Share</strong>: Clorox holds ~2% share in cleaning products, trailing P&amp;G and Colgate-Palmolive .<br>
</li>
<li><strong>Valuation</strong>:
<ul>
<li><strong>P/E Ratio</strong>: 40.5 (FY2024), significantly higher than peers (PG: 26.7, CL: 24.4) .<br>
</li>
<li><strong>Price/Book</strong>: 61.19, inflated due to low equity base ($121M) .</li>
</ul></li>
</ul>
<hr>
</section>
<section id="esg-and-long-term-strategy" class="level4">
<h4 class="anchored" data-anchor-id="esg-and-long-term-strategy"><strong>5. ESG and Long-Term Strategy</strong></h4>
<ul>
<li><strong>IGNITE Strategy</strong>: Focused on digital transformation, consumer-centric innovation, and ESG goals (e.g., 100% recyclable packaging by 2025) .<br>
</li>
<li><strong>Awards</strong>: Recognized as a “Best Company to Work For” and leader in climate action .</li>
</ul>
<hr>
</section>
<section id="outlook-for-fy2025" class="level4">
<h4 class="anchored" data-anchor-id="outlook-for-fy2025"><strong>6. Outlook for FY2025</strong></h4>
<ul>
<li><strong>Revenue</strong>: Projected flat to -2% growth, with organic sales up 3–5% post-divestitures .<br>
</li>
<li><strong>Margin Expansion</strong>: Gross margin expected to rise 100 bps, supported by cost-saving initiatives .<br>
</li>
<li><strong>EPS Guidance</strong>: Adjusted EPS of $6.55–$6.80 (+6–10% YoY) .</li>
</ul>
<hr>
</section>
</section>
<section id="key-takeaways" class="level3">
<h3 class="anchored" data-anchor-id="key-takeaways"><strong>Key Takeaways</strong></h3>
<ol type="1">
<li><strong>Resilience Amid Disruption</strong>: Clorox recovered from the cyberattack but faces lingering debt and liquidity risks .<br>
</li>
<li><strong>Strategic Refocus</strong>: Divestitures and innovation aim to stabilize margins and drive growth in core categories .<br>
</li>
<li><strong>High Valuation Concerns</strong>: Elevated P/E and P/B ratios suggest market optimism but warrant caution given leverage .</li>
</ol>
<p>For detailed financials, refer to Clorox’s <a href="https://investors.thecloroxcompany.com/financial-reporting/annual-reports/default.aspx">FY2024 Annual Report</a> .</p>
</section>
</section>
<section id="forecasting" class="level2">
<h2 class="anchored" data-anchor-id="forecasting">Forecasting</h2>
</section>
<section id="section-6" class="level1 quarto-embed-nb-cell">
<h1></h1>
<ul>
<li>What risks does it list on 10-k? Summarize.</li>
</ul>
<p>Long-term financial forecasting, like all social forecasting, is an incredibly fraught undertaking due to many different reasons (see, for example, [<span class="citation" data-cites="cerqueira8ReasonsWhy2022">Cerqueira (<a href="#ref-cerqueira8ReasonsWhy2022" role="doc-biblioref">2022</a>)</span>] and [<span class="citation" data-cites="ForecastingPredictiveAnalytics"><span>“Forecasting and Predictive Analytics: <span>A</span> Critical Look at the Basic Building Blocks of a Predictive Model”</span> (<a href="#ref-ForecastingPredictiveAnalytics" role="doc-biblioref">n.d.</a>)</span>]). Luckily, many tools are available for us to experiment with.</p>
<p>We’ve already done some simple short-term forecasting in our “Technical Analysis” section using <strong>SMA</strong> and <strong>Bollinger Bands</strong>. We’ve also accessed volatility by calculating <strong>Beta</strong> value and estimated risk/return using <strong>Annualized Sharpe Ratio</strong>, which might help us in medium-term forecasting. Now we will try using advanced <strong>ARIMA</strong> (Auto-Regressive Integrated Moving Averages) to predict stock prices for the next 6 months and for the next year.</p>
<div id="febe19df-5fd3-4ae0-8b5d-f150b60dd3e9" class="cell">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/notebooks-forecasting-cell-2-output-2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8"><img src="index_files/figure-html/notebooks-forecasting-cell-2-output-2.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/notebooks-forecasting-cell-2-output-3.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9"><img src="index_files/figure-html/notebooks-forecasting-cell-2-output-3.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><a href="index_files/figure-html/notebooks-forecasting-cell-2-output-4.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10"><img src="index_files/figure-html/notebooks-forecasting-cell-2-output-4.png" class="img-fluid figure-img"></a></p>
</figure>
</div>
</div>
</div>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
</section>
<section id="section-7" class="level1 quarto-embed-nb-cell">
<h1></h1>
<!--
Can reduce portfolio volatility by pairing inversely correlated securities.
-->
</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-cerqueira8ReasonsWhy2022" class="csl-entry" role="listitem">
Cerqueira, Vitor. 2022. <span>“8 <span>Reasons Why Forecasting Is Hard</span>.”</span> <em>Towards Data Science</em>. https://towardsdatascience.com/8-reasons-why-forecasting-is-hard-481755a05325/.
</div>
<div id="ref-danchoTidyquantTidyQuantitative2025" class="csl-entry" role="listitem">
Dancho, Matt, and Davis Vaughan. 2025. <span>“Tidyquant: <span>Tidy Quantitative Financial Analysis</span>.”</span>
</div>
<div id="ref-FinancialModelingb" class="csl-entry" role="listitem">
<span>“Financial Modeling with <span>R</span>.”</span> n.d. https://mlozanoqf.github.io/tutorial_pmf/. Accessed February 14, 2025.
</div>
<div id="ref-ForecastingPredictiveAnalytics" class="csl-entry" role="listitem">
<span>“Forecasting and Predictive Analytics: <span>A</span> Critical Look at the Basic Building Blocks of a Predictive Model.”</span> n.d. <em>Brookings</em>. https://www.brookings.edu/articles/forecasting-and-predictive-analytics-a-critical-look-at-the-basic-building-blocks-of-a-predictive-model/. Accessed February 15, 2025.
</div>
<div id="ref-IGNITEStrategy" class="csl-entry" role="listitem">
<span>“<span>IGNITE Strategy</span>.”</span> n.d. <em>The Clorox Company</em>. Accessed February 14, 2025.
</div>
<div id="ref-mascellinoCloroxOperationsDisrupted2023" class="csl-entry" role="listitem">
Mascellino, Alessandro. 2023. <span>“Clorox <span>Operations Disrupted By Cyber-Attack</span>.”</span> <em>Infosecurity Magazine</em>. https://www.infosecurity-magazine.com/news/clorox-disrupted-cyber-attack/.
</div>
<div id="ref-PerformanceAnalysisTidyquant" class="csl-entry" role="listitem">
<span>“Performance <span>Analysis</span> with Tidyquant.”</span> n.d. https://business-science.github.io/tidyquant/articles/TQ05-performance-analysis-with-tidyquant.html. Accessed February 14, 2025.
</div>
<div id="ref-PurposeValues" class="csl-entry" role="listitem">
<span>“Purpose &amp; <span>Values</span>.”</span> n.d. <em>The Clorox Company</em>. Accessed February 14, 2025.
</div>
<div id="ref-Quarto" class="csl-entry" role="listitem">
<span>“Quarto.”</span> n.d. <em>Quarto</em>. https://quarto.org/. Accessed February 14, 2025.
</div>
<div id="ref-ProjectStatisticalComputing" class="csl-entry" role="listitem">
<span>“R: <span>The R Project</span> for <span>Statistical Computing</span>.”</span> n.d. https://www.r-project.org/. Accessed February 14, 2025.
</div>
<div id="ref-Recognitions" class="csl-entry" role="listitem">
<span>“Recognitions.”</span> n.d. <em>The Clorox Company</em>. Accessed February 14, 2025.
</div>
<div id="ref-regensteinVisualizationSectorTrends2020" class="csl-entry" role="listitem">
Regenstein, Jonathan. 2020. <span>“Visualization <span>Sector Trends</span> with <span>R Code</span>.”</span> <em>Alpha Architect</em>. https://alphaarchitect.com/2020/01/visualization-sector-trends-with-r-code/.
</div>
<div id="ref-Responsibility" class="csl-entry" role="listitem">
<span>“Responsibility.”</span> n.d. <em>The Clorox Company</em>. Accessed February 14, 2025.
</div>
<div id="ref-CloroxCompanyCLX" class="csl-entry" role="listitem">
<span>“The <span>Clorox Company</span> (<span>CLX</span>) <span>Company Profile</span> &amp; <span>Facts</span>.”</span> n.d. <em>Yahoo Finance</em>. https://finance.yahoo.com/quote/CLX/profile/. Accessed February 13, 2025.
</div>
<div id="ref-CloroxCompanyCLXa" class="csl-entry" role="listitem">
<span>“The <span>Clorox Company</span> (<span>CLX</span>) <span>Leadership</span> &amp; <span>Management Team Analysis</span>.”</span> n.d. <em>Simply Wall St</em>. https://simplywall.st/stocks/us/household/nyse-clx/clorox/management. Accessed February 14, 2025.
</div>
<div id="ref-CloroxCompanyBusiness" class="csl-entry" role="listitem">
<span>“The <span>Clorox Company</span>: <span>Business Model</span>, <span>SWOT Analysis</span>, and <span>Competitors</span> 2024 - <span>PitchGrade</span>.”</span> n.d. https://pitchgrade.com/companies/the-clorox-company. Accessed February 13, 2025.
</div>
<div id="ref-CloroxMarketShare" class="csl-entry" role="listitem">
<span>“The <span>Clorox Market</span> Share Relative to Its Competitors, as of <span>Q4</span> 2024 - <span>CSIMarket</span>.”</span> n.d. https://csimarket.com/stocks/competitionSEG2.php?code=CLX. Accessed February 14, 2025.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>