{
  "hash": "fe92c7fd3cca3931075484114acaf7f6",
  "result": {
    "engine": "knitr",
    "markdown": "<!--\nCommon size analysis for fundamental analysis.\nLife cycle stage.\nROI for stock over a period of time.\nAnalyst's views and rating.\nclient.shwab.com\nEBITDA\nP/B ratio\nEV = Mcap + Debt\n-->\n\n---\n\n::: {.callout-important}\nIn this section we will take a look at quantitative fundamental analysis tools provided by the \"tidyquant\" R language package [@danchoTidyquantTidyQuantitative2025] and use them to get key financial ratios of fundamental analysis for the Clorox company. This section is based on the following wonderful tutorial: @PerformanceAnalysisTidyquant\n:::\n\nFirst let's retrieve 5-year period returns from the prices adjusted for stock splits, both for Clorox and S&P500 as the baseline. Next, we combine both datasets (Clorox and S&P500 returns) using \"left-join\" on the \"date\" field. Using this dataset, we can retrieve all kind of fundamental metrics, such as **Alpha** (0.0008), **Beta** (0.414).\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.4     ✔ tidyr     1.3.1\n✔ purrr     1.0.4     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ purrr::%||%()   masks base::%||%()\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(tidyquant)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRegistered S3 method overwritten by 'quantmod':\n  method            from\n  as.zoo.data.frame zoo \n── Attaching core tidyquant packages ─────────────────────── tidyquant 1.0.10 ──\n✔ PerformanceAnalytics 2.0.8      ✔ TTR                  0.24.4\n✔ quantmod             0.4.26     ✔ xts                  0.14.1── Conflicts ────────────────────────────────────────── tidyquant_conflicts() ──\n✖ purrr::%||%()                  masks base::%||%()\n✖ zoo::as.Date()                 masks base::as.Date()\n✖ zoo::as.Date.numeric()         masks base::as.Date.numeric()\n✖ dplyr::filter()                masks stats::filter()\n✖ xts::first()                   masks dplyr::first()\n✖ dplyr::lag()                   masks stats::lag()\n✖ xts::last()                    masks dplyr::last()\n✖ PerformanceAnalytics::legend() masks graphics::legend()\n✖ quantmod::summary()            masks base::summary()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nRa <- \"CLX\" |>\n    tq_get(get  = \"stock.prices\",\n           from = \"2020-01-01\",\n           to   = \"2025-02-01\") |>\n    group_by(symbol) |>\n    tq_transmute(select     = adjusted, \n                 mutate_fun = periodReturn, \n                 period     = \"monthly\", \n                 col_rename = \"Ra\")\n\n\nRb <- \"^GSPC\" |>\n    tq_get(get  = \"stock.prices\",\n           from = \"2020-01-01\",\n           to   = \"2025-02-01\") |>\n    tq_transmute(select     = adjusted, \n                 mutate_fun = periodReturn, \n                 period     = \"monthly\", \n                 col_rename = \"Rb\")\n\nRaRb <- left_join(Ra, Rb, by = c(\"date\" = \"date\"))\n\n\nRaRb_capm <- RaRb %>%\n    tq_performance(Ra = Ra, \n                   Rb = Rb, \n                   performance_fun = table.CAPM)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nRegistered S3 method overwritten by 'robustbase':\n  method          from     \n  hatvalues.lmrob RobStatTM\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nRaRb_capm %>% select(symbol, Alpha, Beta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n# Groups:   symbol [1]\n  symbol  Alpha  Beta\n  <chr>   <dbl> <dbl>\n1 CLX    0.0008 0.414\n```\n\n\n:::\n:::\n\n\n\nWe can also get the **Sharpe Ratio** by following the similar steps (no need for the baseline this time).\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(tidyverse)\nlibrary(tidyquant)\n\nRa <- \"CLX\" |>\n    tq_get(get  = \"stock.prices\",\n           from = \"2020-01-01\",\n           to   = \"2025-02-01\") |>\n    group_by(symbol) |>\n    tq_transmute(select     = adjusted, \n                 mutate_fun = periodReturn, \n                 period     = \"monthly\", \n                 col_rename = \"Ra\")\n\nRa |>\n  tq_performance(\n        Ra = Ra, \n        Rb = NULL, \n        performance_fun = SharpeRatio\n    )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 5\n# Groups:   symbol [1]\n  symbol `ESSharpe(Rf=0%,p=95%)` SemiSDSharpe(Rf=0%,p=9…¹ StdDevSharpe(Rf=0%,p…²\n  <chr>                    <dbl>                    <dbl>                  <dbl>\n1 CLX                     0.0438                   0.0822                 0.0782\n# ℹ abbreviated names: ¹​`SemiSDSharpe(Rf=0%,p=95%)`,\n#   ²​`StdDevSharpe(Rf=0%,p=95%)`\n# ℹ 1 more variable: `VaRSharpe(Rf=0%,p=95%)` <dbl>\n```\n\n\n:::\n:::\n\n\n\n#### **I. Graham Number Calculation**  \nThe Graham Number estimates a stock’s intrinsic value using earnings per share (EPS) and book value per share (BVPS):  \n**Formula**:  \n\n$$\\text{Graham Number} = \\sqrt{22.5 \\times \\text{EPS} \\times \\text{BVPS}}$$\n\n- **EPS (TTM)**: $3.67   \n- **BVPS**: $0.98 (Total Equity: $121M / Shares Outstanding: 123.19M)   \n- **Calculation**:  \n$$\\sqrt{22.5 \\times 3.67 \\times 0.98} = \\sqrt{80.92} \\approx \\boxed{8.99}$$\n- **Interpretation**: CLX’s current stock price (~$149.61) far exceeds the Graham Number, indicating potential overvaluation based on traditional metrics .  \n\n---\n\n#### **II. Key Financial Ratios**  \n\n| **Category**       | **Ratio**                   | **CLX Value**               | **Formula**                                                                 | **Interpretation**                                                                 |\n|---------------------|-----------------------------|------------------------------|-----------------------------------------------------------------------------|-----------------------------------------------------------------------------------|\n| **Profitability**   | Gross Profit Margin         | 44.51%           | (Revenue - COGS) / Revenue                                                  | Stable gross margins despite cost inflation, supported by cost-saving initiatives . |\n|                     | Operating Profit Margin     | 14.32%           | Operating Income / Revenue                                                  | Margin expansion driven by divestitures and operational recovery post-cyberattack . |\n|                     | Net Profit Margin           | 6.38%            | Net Income / Revenue                                                        | Lower than peers (e.g., P&G: ~18%), reflecting cyberattack recovery costs . |\n|                     | Return on Assets (ROA)      | 11.17%            | Net Income / Avg. Total Assets                                              | Efficient asset utilization, though impacted by divestitures . |\n|                     | Return on Equity (ROE)      | 276.11%           | Net Income / Avg. Shareholders’ Equity                                      | Artificially high due to low equity base ($121M) . |\n| **Liquidity**       | Current Ratio               | 0.94              | Current Assets / Current Liabilities                                        | Below industry norms (1.5–3.0), indicating liquidity strain . |\n|                     | Quick Ratio                 | 0.52              | (Cash + Receivables) / Current Liabilities                                  | Limited near-term liquidity, with heavy reliance on receivables . |\n| **Solvency**        | Debt-to-Equity Ratio        | 25.55             | Total Liabilities / Shareholders’ Equity                                   | Extremely high leverage (vs. industry median ~1.0), raising solvency concerns . |\n|                     | Debt-to-Assets Ratio        | 98%               | Total Liabilities / Total Assets                                           | Nearly all assets financed by debt, increasing bankruptcy risk . |\n|                     | Interest Coverage Ratio     | ~11.7  | Operating Income / Interest Expense                                        | Strong coverage due to operational recovery, but debt levels remain risky. |\n| **Efficiency**      | Asset Turnover Ratio        | 1.25              | Revenue / Avg. Total Assets                                                 | Efficient asset use, though lower than pre-cyberattack levels . |\n|                     | Inventory Turnover Ratio    | 6.38              | COGS / Avg. Inventory                                                       | Healthy turnover, but down from 7.57 in 2020 . |\n|                     | Receivables Turnover Ratio  | ~11.05  | Revenue / Avg. Accounts Receivable                                         | Faster collections than industry median (~30 days) . |\n| **Valuation**       | P/E Ratio                   | 40.50             | Price per Share / EPS                                                       | High vs. peers (PG: 26.66, CL: 24.39), reflecting recovery optimism . |\n|                     | P/B Ratio                   | 61.19             | Price per Share / Book Value per Share                                     | Extremely high, driven by low equity base and market premium . |\n|                     | P/S Ratio                   | 2.59              | Price per Share / Revenue per Share                                        | Aligns with sector norms (Consumer Staples avg: ~2.5–3.0) . |\n|                     | Dividend Yield              | 3.26%             | Annual Dividend / Price per Share                                          | Attractive yield, supported by 48-year dividend growth streak . |\n\n---\n\n#### **III. Key Insights**  \n1. **Profitability**: Margins are recovering post-cyberattack, but net margins lag competitors. Gross margin improved to 43.8% in Q2 FY25, with cost savings offsetting inflation .  \n2. **Liquidity Risks**: Low current (0.94) and quick (0.52) ratios highlight liquidity challenges, though improved cash flow ($401M YTD) provides relief .  \n3. **Debt Concerns**: Debt-to-equity (25.55) and debt-to-assets (98%) ratios signal high leverage, though interest coverage (11.7x) remains manageable .  \n4. **Valuation**: Elevated P/E (40.5) and P/B (61.19) suggest market optimism about Clorox’s recovery, but Graham Number ($8.99) implies overvaluation .  \n5. **Dividend Strength**: A 3.26% yield with consistent growth underscores Clorox’s defensive appeal, despite a high payout ratio (133%) .  \n\n---\n\n#### **IV. Conclusion**  \nClorox’s fundamentals reflect a company in recovery, balancing strong brand equity and dividend reliability with significant debt and valuation risks. While operational improvements (e.g., margin expansion, ERP transition) are promising, the stock’s premium pricing and leverage warrant caution. Investors should monitor debt reduction and margin sustainability in 2025 .\n",
    "supporting": [
      "fundamentals_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}